from uwimg import *
im = load_image("data/dog.jpg")
f = make_box_filter(7)
blur = convolve_image(im, f, 1)
save_image(blur, "dog-box7")
thumb = nn_resize(blur, blur.h//7, blur.w//7)
save_image(thumb, "dogthumb")
f_gauss = make_gaussian_filter(2)
blur_gauss = convolve_image(im, f_gauss, 1)
save_image(blur_gauss, "dog-gauss2")
f_emboss = make_emboss_filter()
im_emboss = convolve_image(im, f_emboss, 0)
save_image(im_emboss, "dog-emboss-mono")
f_highpass = make_highpass_filter()
im_highpass = convolve_image(im, f_highpass, 1)
save_image(im_highpass, "dog-highpass")
f_sharpen = make_sharpen_filter()
im_sharpen = convolve_image(im, f_sharpen, 0)
save_image(im_sharpen, "dog-sharpen-mono")
im_add = add_image(im_highpass, blur_gauss)
save_image(im_add, "dog-add")
